### ISSUE TITLE
Missing file: em_input.mat

### ISSUE THREAD

**Issue by alowet** [harvineet/py-gpfa#1]
Thanks for writing this toolbox. It looks super useful.

I am just starting out and trying to run the code on simulated data. However, running `python data_simulator.py` throws the error `No such file or directory: 'em_input.mat'`. I can't find this file anywhere and suspect that it's missing from the repository. Can you please add such an example parameter file so that I can proceed — or else tell me what I'm missing here? Thank you very much.

**Comment by harvineet** [comment]
@alowet Added files with simulated data in a new folder named input. Modified example.py to read the new files.
https://github.com/harvineet/py-gpfa/commit/36eaf489c57270b20dd6425298e75347683e5f2c

You can try running example.py which should create plots in output folder. Let me know if that works.

**Comment by alowet** [comment]
`python example.py` now runs correctly, and figures are plotted and saved to the output folder. After fitting and cross-validation, the final output looks like this:

```
LL for training: -15653.5804, for testing: -8205.0776, method: gpfa, x_dim:4, param_cov_type:rbf, param_Q:2
True and predicted latent state dimensions do not match
Mean sequared error across trials: inf
True and predicted latent state dimensions do not match
R^2 averaged across trials: [nan nan nan nan]
True and predicted latent state dimensions do not match
True and predicted latent state dimensions do not match
True and predicted latent state dimensions do not match
True and predicted latent state dimensions do not match
```
Is this the expected behavior?

**Comment by harvineet** [comment]
Yes, that is expected as the fake data was generated with a different number of latent dimensions. Apologies for not documenting this very well.
Corrected example.py with correct `x_dim`. The warning should be resolved now. Plots will show predicted trajectories.
Hope this re-implementation is useful.

**Comment by alowet** [comment]
Thanks so much! Output looks normal now. I look forward to using this on my own data.
