### ISSUE TITLE
Generalization performance assessment fails with trials of different lengths

### ISSUE THREAD

**Issue by alowet** [harvineet/py-gpfa#2]
Solution: lines 30-31 of cosmoother_gpfa_viaOrth_fast.py should be 
```
for i in range(len(seq)):
    out_seq.append( {'dim'+str(key): np.empty((yDim, seq[i].T)) * np.nan for key in mList} )
```
instead of 
```
for i in range(len(seq)):
     out_seq.append( {'dim'+str(key): np.empty((yDim, seq[key].T)) * np.nan for key in mList} )
```

**Comment by harvineet** [comment]
Yes, that is a good catch. Do you want to create a pull request or should I directly rectify. Thanks!

About pull requests: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

**Comment by alowet** [comment]
Submitted the pull request.
